# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.7
  - 1.0
notifications:
  email: false
addons:
  apt:
    packages:
      - python3
      - python3-pip
before_install:
  - pip3 --user install numpy
  - pip3 --user install Cython
  - pip3 --user install pandas
